language: java
sudo: true # false for faster builds
script: "mvn -f MatematikUygulamasi/pom.xml clean install cobertura:cobertura checkstyle:checkstyle pmd:pmd javadoc:javadoc javadoc:aggregate site -Dmaven.javadoc.skip=false"
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
after_success:
  - bash <(curl -s https://codecov.io/bash)
